author/urls.py
from django.urls import path

from . import views


app_name = 'author'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('<int:pk>/', views.detail, name='detail'),
]

book/urls.py
from django.urls import path

from . import views


app_name = 'book'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

core/urls.py
from django.urls import path

from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

readr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('author.urls')),
    path('books/', include('book.urls')),
    path('', include('core.urls')),
]

author/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

book/models.py
from django.db import models

from author.models import Author


class Book(models.Model):
    WANTED = 'wanted'
    WAITING = 'waiting'
    READING = 'reading'
    READ = 'read'

    STATUS_CHOICES = (
        (WANTED, 'Wanted'),
        (WAITING, 'Waiting'),
        (READING, 'Reading'),
        (READ, 'Read')
    )

    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, related_name='books', on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=WAITING)

    class Meta:
        ordering = ('title',)

core/models.py
from django.db import models

# Create your models here.

author/forms.py
from django.forms import ModelForm

from .models import Author


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ('name',)

book/forms.py
from django.forms import ModelForm

from .models import Book


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'status',)

author/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AuthorForm
from .models import Author


def index(request):
    authors = Author.objects.all()

    return render(request, 'author/index.html', {
        'authors': authors
    })


def detail(request, pk):
    author = get_object_or_404(Author, pk=pk)

    return render(request, 'author/detail.html', {
        'author': author
    })


def add(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('author:index')
    else:
        form = AuthorForm()

    return render(request, 'author/add.html', {
        'form': form
    })

book/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import BookForm
from .models import Book


def index(request):
    books = Book.objects.all()

    return render(request, 'book/index.html', {
        'books': books
    })


def detail(request, pk):
    book = get_object_or_404(Book, pk=pk)

    return render(request, 'book/detail.html', {
        'book': book
    })


def add(request):
    if request.method == 'POST':
        form = BookForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('book:index')
    else:
        form = BookForm()

    return render(request, 'book/add.html', {
        'form': form
    })


def edit(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)

        if form.is_valid():
            form.save()

            return redirect('book:index')
    else:
        form = BookForm(instance=book)
    
    return render(request, 'book/edit.html', {
        'form': form
    })


def delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    book.delete()

    return redirect('book:index')

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')

author/templates/author/add.html
{% extends 'core/base.html' %}

{% block title %}Add author{% endblock %}

{% block content %}
    <h1 class="text-2xl">Add author</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-6 bg-sky-700 text-white">Submit</button>
    </form>
{% endblock %}

author/templates/author/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ author.name }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">{{ author.name }}</h1>

    {% if author.books.count %}
        {% for book in author.books.all %}
            <div class="p-4 grid grid-cols-2 gap-4 bg-slate-100">
                <h2>
                    <a href="{% url 'book:detail' book.id %}">{{ book.title }}</a>
                </h2>

                <p>{{ book.get_status_display }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>This author doesn't have any books yet...</p>
    {% endif %}
{% endblock %}

author/templates/author/index.html
{% extends 'core/base.html' %}

{% block title %}Authors{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">Authors</h1>

    <a href="{% url 'author:add' %}" class="mb-6 py-4 px-6 inline-block bg-sky-700 text-white">Add author</a>
    
    <div class="space-y-4">
        {% for author in authors %}
            <div class="py-4 px-6 bg-slate-100">
                <a href="{% url 'author:detail' author.id %}">{{ author.name }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

book/templates/book/add.html
{% extends 'core/base.html' %}

{% block title %}Add book{% endblock %}

{% block content %}
    <h1 class="text-2xl">Add book</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-6 bg-sky-700 text-white">Submit</button>
    </form>
{% endblock %}

book/templates/book/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">{{ book.title }}</h1>

    <h3><strong>Status:</strong> {{ book.get_status_display }}</h3>
    <h3><strong>Author:</strong> <a href="{% url 'author:detail' book.author.id %}">{{ book.author.name }}</a></h3>

    <a href="{% url 'book:edit' book.id %}" class="mt-6 py-4 px-6 inline-block bg-sky-700 text-white">Edit</a>
    <a href="{% url 'book:delete' book.id %}" class="mt-6 py-4 px-6 inline-block bg-amber-700 text-white">Delete</a>
{% endblock %}

book/templates/book/edit.html
{% extends 'core/base.html' %}

{% block title %}Edit book{% endblock %}

{% block content %}
    <h1 class="text-2xl">Edit book</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-6 bg-sky-700 text-white">Save changes</button>
    </form>
{% endblock %}

book/templates/book/index.html
{% extends 'core/base.html' %}

{% block title %}Books{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">Books</h1>

    {% if books%}
        {% for book in books %}
            <div class="p-4 grid grid-cols-2 gap-4 bg-slate-100">
                <h2>
                    <a href="{% url 'book:detail' book.id %}">{{ book.title }}</a>
                </h2>

                <p>{{ book.get_status_display }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>You don't have any books yet...</p>
    {% endif %}
{% endblock %}

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="max-w-4xl mx-auto py-6 px-8 flex justify-between items-center bg-slate-800">
            <a href="/" class="text-2xl text-white">Readr</a>

            <div class="space-x-6">
                <a href="{% url 'book:index' %}" class="text-white">Books</a>
                <a href="{% url 'author:index' %}" class="text-white">Authors</a>

                <a href="{% url 'book:add' %}" class="py-4 px-6 bg-sky-700 text-white">Add book</a>
            </div>
        </nav>

        <div class="max-w-4xl mx-auto py-6 px-8">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome to Readr{% endblock %}

{% block content %}
this is the content
{% endblock %}